[package]
name = "zeus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zeus"
path = "src/zeus.rs"

[[bin]]
name = "builder"
path = "src/builder.rs"

[dependencies]
termcolor = "1.1.3"
args = "2.2.0"
getopts = "0.2.21"
tokio = {version = "1.17.0",  features = ["full"] }
futures = "0.3.21"
bollard = "0.12.0"
serde = "1.0.117"
serde_json = "1.0.59"