[package]
name = "zeus"
version = "0.1.0"
edition = "2021"
authors = ["threadexio"]
description = "Containerized AUR helper"
readme = "README.md"
homepage = "https://github.com/threadexio/zeus"
repository = "https://github.com/threadexio/zeus"
license = "GPL-3.0-or-later"

[[bin]]
name = "zeus"
path = "src/zeus.rs"

# TODO: rewrite builder
#[[bin]]
#name = "builder"
#path = "src/builder.rs"

[lib]
name = "zeus"
path = "src/lib.rs"


[dependencies]
colored = "2"
inquire = "0.4"
clap = { version = "4.0", features = ["cargo", "derive"] }
clap_complete = "4.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
channels = "0.5.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }

fs4 = { version = "0.6", features = ["sync"] }
libloading = "0.7"

const_format = "0.2"
thiserror = "1.0"

[workspace]
members = ["runtimes/zeus_rt_docker"]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = "off"
strip = false

[profile.release]
opt-level = "s"
debug = false
debug-assertions = false
overflow-checks = true
lto = "fat"
strip = "debuginfo"
