[package]
name = "zeus"
version = "0.1.0"
edition = "2021"
description = "Containerized AUR helper"
readme = "README.md"
homepage = "https://github.com/threadexio/zeus"
repository = "https://github.com/threadexio/zeus"
license = "GPL-3.0-or-later"

[[bin]]
name = "zeus"
path = "src/zeus.rs"

[[bin]]
name = "builder"
path = "src/builder.rs"

[dependencies]
termcolor = "^1.1"
clap = { version = "^3.1", features = ["cargo"] }
clap_complete = "^3.1"
tokio = { version = "^1.18", features = ["full"] }
futures = "^0.3"
bollard = "0.12.0"
serde = "^1.0"
serde_json = "^1.0"
fs4 = { version = "^0.5", features = ["sync"] }
ctrlc = { version = "^3.2", features = ["termination"] }
const_format = "^0.2"
default-env = "^0.1"
reqwest = { version = "^0.11", features = ["json"] }
