[package]
name = "zeus"
version = "0.1.0"
edition = "2021"
authors = ["threadexio"]
description = "Containerized AUR helper"
readme = "README.md"
homepage = "https://github.com/threadexio/zeus"
repository = "https://github.com/threadexio/zeus"
license = "GPL-3.0-or-later"

[lib]
name = "zeus"
path = "src/lib.rs"

[[bin]]
name = "zeus"
path = "src/zeus.rs"

[[bin]]
name = "builder"
path = "src/builder.rs"

[dependencies]
clap = { version = "^3.1", features = ["cargo"] }
clap_complete = "^3.1"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
fs4 = { version = "^0.5", features = ["sync"] }
const_format = "^0.2"
default-env = "^0.1"
reqwest = { version = "^0.11", features = ["json", "blocking"] }
colored = "^2.0"
libloading = "^0.7"

[workspace]
members = ["runtimes/zeus_rt_docker"]
