[package]
name = "zeus"
edition = "2021"
version = "0.1.0"
authors = ["threadexio <pzarganitis@gmail.com>"]
description = "Containerized AUR helper"
homepage = "https://github.com/threadexio/zeus"
repository = "https://github.com/threadexio/zeus"
license = "GPL-3.0-or-later"
readme = "README.md"

build = "build.rs"
publish = false
default-run = "zeus"

[lib]
name = "zeus"
path = "src/lib.rs"

[[bin]]
name = "zeus"
path = "src/main.rs"

[[bin]]
name = "builder"
path = "src/builder.rs"

[dependencies]
thiserror = "1.0"
const_format = { version = "0.2" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "blocking"] }
channels = "0.5.0"
toml = "0.5"

clap = { version = "3.2.23", features = ["cargo", "derive"] }
clap_complete = { version = "3.2.5" }
inquire = "0.4"
colored = "2"

fs4 = { version = "0.6", features = ["sync"] }
nix = { version = "0.25", features = ["fs"] }
libloading = "0.7"

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[workspace]
members = ["runtimes/*"]
