max_width = 70
hard_tabs = true
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Off"
fn_call_width = 60
attr_fn_like_width = 60
struct_lit_width = 60
struct_variant_width = 60
array_width = 60
chain_width = 60
single_line_if_else_max_width = 0
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
match_arm_leading_pipes = "Never"
fn_params_layout = "Tall"
match_block_trailing_comma = true
edition = "2021"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
