[package]
name = "zeus-rt"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[dependencies]
anyhow = { workspace = true }
libloading = { workspace = true }
thiserror = { workspace = true }
xxhash-rust = { workspace = true }

zeus-types = { workspace = true }
zeus-term = { workspace = true }
