## <-- The hashtag or the pound sign (#) is used to comment out a line.
##     Commenting out a line means that it will be ignored. So If you need
##     To make any changes bellow, you should remove the '#' in front.

##
## This section configures the logger for zeus.
##
[log]
# The default log level. (--level)
#Level = "info"

##
## This section configures the AUR
## zeus will try and communicate with.
##
[aur]
# The default AUR url. (--aur)
#Url = "https://aur.archlinux.org"

##
## This section configures the
## runtime zeus will use.
##
[runtime]
# The runtime that will be used by default. (--runtime)
#Name = "docker"

# The builder's name. (--name)
#BuilderName = "zeus-builder"

# The builder's base image. (--image)
#BuilderImage = "zeus-builder"

##
## This section configures the
## general environment of zeus.
##
[zeus]
# When to use colored terminal output. (--color)
#Color = "auto"

# The default package build directory. (--build-dir)
#BuildDir = "/var/cache/aur"

##
## Default options for when syncing packages.
##
[zeus.sync]
# Should we also try to upgrade the packages? (--upgrade)
#Upgrade = false

# Should we also try to install the packages
# with pacman? (--install)
#
# WARNING: Changing this option to true has security implications!
#          See: ArchWiki Arch User Repository ยง 3.4 Build the package.
#          https://wiki.archlinux.org/title/Arch_User_Repository#Build_the_package
#Install = false

# Extra arguments to pass to makepkg when building the packages. (--build-args)
#ExtraArgs = []

##
## Default options for when removing packages.
##
[zeus.remove]
# Should we try to uninstall the packages with pacman? (--uninstall)
#Uninstall = false

##
## Default options for querying the AUR
##
[zeus.query]
# How should we match packages?
# Valid values:
#   name           Match by package name
#   namedesc       Match by package name and description
#   maintainer     Match by maintainer name
#   depends        Match by dependency
#   makedepends    Match by dev dependency
#   optdepends     Match by optional dependency
#   checkdepends   Match by test dependency
#By = "namedesc"

# How should we display the results?
# Valid values:
#   pretty         Display the results in a human-readable format
#   json           Display the results in JSON
#Output = "pretty"

##
## Default options for generating completions
##
[zeus.completions]
# The default shell. (--shell)
# Valid values:
#  bash
#  fish
#  zsh
#Shell = "bash"
