name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  default: true

            - run: |
                case "${GITHUB_REF}" in ref/tags*)
                    export VERSION="${GITHUB_REF#refs/tags/}"
                esac

                make BUILD_TYPE=release package

            - uses: actions/upload-artifact@v3
              with:
                  name: zeus-bin.tar.gz
                  path: zeus-bin.tar.gz

            - uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: zeus-bin.tar.gz