name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - run: |
          make BUILD_TYPE=release PREFIX="/usr" package

      - uses: actions/upload-artifact@v3
        with:
          name: zeus-bin
          path: |
            builder.tar.gz
            target/release/zeus
            zeus-bin.tar.gz

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: zeus-bin.tar.gz
