name: Build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - uses: actions-rs/toolchain@v1
              with:
                  profile: default
                  toolchain: stable
                  default: true

            - uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --release

            - uses: actions/upload-artifact@v3
              with:
                  name: release ubuntu-latest
                  path: |
                      target/release/zeus*
                      !target/release/zeus.d
                      target/release/builder*
                      !target/release/builder.d
