name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!startsWith(github.event.head_commit.message, '[no-ci]')"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup toolchain
              uses: actions-rs/toolchain@v1

            - name: CI
              run: |
                  make PROFILE=release ci-flow

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: zeus
                  path: |
                      zeus.tar.gz

            - name: Create release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  files: zeus.tar.gz
