name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container: docker.io/archlinux/archlinux:base-devel
        if: "!startsWith(github.event.head_commit.message, '[no-ci]')"

        steps:
            - name: Setup machine
              run: |
                  useradd -m builder

            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup toolchain
              uses: actions-rs/toolchain@v1

            - name: Build
              run: |
                  make PROFILE=release ci-flow

            - name: Package
              run: |
                  mkdir -p /install
                  chown -R -v builder:builder /install
                  sudo -u builder make DESTDIR=/install tar pkg

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: zeus
                  path: |
                      zeus.tar.gz
                      pkg/zeus-bin-*.pkg.tar.zst

            - name: Create release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/v')
              with:
                  draft: true
                  fail_on_unmatched_files: true
                  generate_release_notes: true
                  files: |
                      zeus.tar.gz
                      pkg/zeus-bin-*.pkg.tar.zst
