name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - run: |
          make BUILD_TYPE=release build

      - uses: actions/upload-artifact@v3
        with:
          name: zeus-bin
          path: |
            builder.tar.gz
            target/release/zeus

      - uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'push' }} && ${{ startsWith(github.event.ref, 'ref/tags/') }}
        with:
          files: zeus-bin.tar.gz