name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      - run: |
          make BUILD_TYPE=release build

      - uses: softprops/action-gh-release@v1
        with:
          files: zeus-bin.tar.gz